var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/roadmap/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__e8aff594._.js")
R.c("server/chunks/ssr/_472c1382._.js")
R.c("server/chunks/ssr/_9b1b330c._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2d316e1b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_87b4f8c7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_279ffcdc._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__32816ccd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/[root-of-the-server]__b8940275._.js")
R.c("server/chunks/ssr/_366121aa._.js")
R.m(38311)
module.exports=R.m(38311).exports
