var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/senpai/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__22a50738._.js")
R.c("server/chunks/ssr/_472c1382._.js")
R.c("server/chunks/ssr/_4e4cfc1d._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2d316e1b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_87b4f8c7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_279ffcdc._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__32816ccd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_senpai_page_actions_ef82106c.js")
R.m(42220)
module.exports=R.m(42220).exports
