// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/blog-hunter" | "/contests" | "/dashboard" | "/dashboard/flashback" | "/flashback" | "/guide" | "/interview" | "/link-handle" | "/login" | "/playlist" | "/racer" | "/resources" | "/roadmap" | "/selector" | "/senpai" | "/skills" | "/stress" | "/studio"
type AppRouteHandlerRoutes = "/api/ai/blog-search" | "/api/ai/hint" | "/api/auth/[...nextauth]" | "/api/dojo/assist" | "/api/dojo/judge" | "/api/dojo/verify-cf" | "/api/dojo/verify-template" | "/api/flashback/generate-quiz" | "/api/interview/interrupt" | "/api/interview/refactor" | "/api/interview/start" | "/api/ml/predict" | "/api/ml/search" | "/api/oauth/callback" | "/api/oauth/login" | "/api/playlist/generate" | "/api/run" | "/api/status"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/ai/blog-search": {}
  "/api/ai/hint": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/dojo/assist": {}
  "/api/dojo/judge": {}
  "/api/dojo/verify-cf": {}
  "/api/dojo/verify-template": {}
  "/api/flashback/generate-quiz": {}
  "/api/interview/interrupt": {}
  "/api/interview/refactor": {}
  "/api/interview/start": {}
  "/api/ml/predict": {}
  "/api/ml/search": {}
  "/api/oauth/callback": {}
  "/api/oauth/login": {}
  "/api/playlist/generate": {}
  "/api/run": {}
  "/api/status": {}
  "/blog-hunter": {}
  "/contests": {}
  "/dashboard": {}
  "/dashboard/flashback": {}
  "/flashback": {}
  "/guide": {}
  "/interview": {}
  "/link-handle": {}
  "/login": {}
  "/playlist": {}
  "/racer": {}
  "/resources": {}
  "/roadmap": {}
  "/selector": {}
  "/senpai": {}
  "/skills": {}
  "/stress": {}
  "/studio": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
