// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../app/blog-hunter/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog-hunter">> = Specific
  const handler = {} as typeof import("../../../app/blog-hunter/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/contests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contests">> = Specific
  const handler = {} as typeof import("../../../app/contests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/flashback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard/flashback">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/flashback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/flashback/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/flashback">> = Specific
  const handler = {} as typeof import("../../../app/flashback/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/guide/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/guide">> = Specific
  const handler = {} as typeof import("../../../app/guide/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/interview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/interview">> = Specific
  const handler = {} as typeof import("../../../app/interview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/link-handle/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/link-handle">> = Specific
  const handler = {} as typeof import("../../../app/link-handle/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/playlist/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/playlist">> = Specific
  const handler = {} as typeof import("../../../app/playlist/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/racer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/racer">> = Specific
  const handler = {} as typeof import("../../../app/racer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources">> = Specific
  const handler = {} as typeof import("../../../app/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/roadmap/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/roadmap">> = Specific
  const handler = {} as typeof import("../../../app/roadmap/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/selector/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/selector">> = Specific
  const handler = {} as typeof import("../../../app/selector/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/senpai/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/senpai">> = Specific
  const handler = {} as typeof import("../../../app/senpai/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/skills/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/skills">> = Specific
  const handler = {} as typeof import("../../../app/skills/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/stress/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/stress">> = Specific
  const handler = {} as typeof import("../../../app/stress/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/studio/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/studio">> = Specific
  const handler = {} as typeof import("../../../app/studio/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/blog-search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/blog-search">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/blog-search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ai/hint/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai/hint">> = Specific
  const handler = {} as typeof import("../../../app/api/ai/hint/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dojo/assist/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dojo/assist">> = Specific
  const handler = {} as typeof import("../../../app/api/dojo/assist/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dojo/judge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dojo/judge">> = Specific
  const handler = {} as typeof import("../../../app/api/dojo/judge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dojo/verify-cf/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dojo/verify-cf">> = Specific
  const handler = {} as typeof import("../../../app/api/dojo/verify-cf/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/dojo/verify-template/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dojo/verify-template">> = Specific
  const handler = {} as typeof import("../../../app/api/dojo/verify-template/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/flashback/generate-quiz/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/flashback/generate-quiz">> = Specific
  const handler = {} as typeof import("../../../app/api/flashback/generate-quiz/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/interview/interrupt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/interview/interrupt">> = Specific
  const handler = {} as typeof import("../../../app/api/interview/interrupt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/interview/refactor/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/interview/refactor">> = Specific
  const handler = {} as typeof import("../../../app/api/interview/refactor/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/interview/start/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/interview/start">> = Specific
  const handler = {} as typeof import("../../../app/api/interview/start/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ml/predict/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ml/predict">> = Specific
  const handler = {} as typeof import("../../../app/api/ml/predict/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/ml/search/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ml/search">> = Specific
  const handler = {} as typeof import("../../../app/api/ml/search/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/oauth/callback/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/callback">> = Specific
  const handler = {} as typeof import("../../../app/api/oauth/callback/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/oauth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/oauth/login">> = Specific
  const handler = {} as typeof import("../../../app/api/oauth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/playlist/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/playlist/generate">> = Specific
  const handler = {} as typeof import("../../../app/api/playlist/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/run/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/run">> = Specific
  const handler = {} as typeof import("../../../app/api/run/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../app/api/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/status">> = Specific
  const handler = {} as typeof import("../../../app/api/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
