var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/contests/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__33d1116c._.js")
R.c("server/chunks/ssr/_472c1382._.js")
R.c("server/chunks/ssr/_930ce9c9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__2d316e1b._.js")
R.c("server/chunks/ssr/node_modules_next_dist_87b4f8c7._.js")
R.c("server/chunks/ssr/node_modules_next_dist_279ffcdc._.js")
R.c("server/chunks/ssr/app_b9b1292a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__32816ccd._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_contests_page_actions_d30260f3.js")
R.m(63615)
module.exports=R.m(63615).exports
